# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfa56d18e24e3a96e2a83138bacc52159f9ac2d4f0b36734e78e83e35cb7c994f1a516f267bf506fbff02395e1af153ac0c609a8705ebbade2f6963b72cbaf18

test:
  secret_key_base: 34bb60c3f217df29b5d48da2a1bf99c7e0f135b13f3c119fc4920eef22a3559bf0fd04d1925b63e7519ec3e60fbd234ab50bd5552749243658dabdcaacfa43ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
